version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: messagepulse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: messagepulse
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: messagepulse-adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
